// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjymWtOgn_YtKlG7nSM4z2A6WZ7x7sndk',
    appId: '1:636444728768:web:d96f1916c0ad8163f7fc25',
    messagingSenderId: '636444728768',
    projectId: 'popcorntime-4b65b',
    authDomain: 'popcorntime-4b65b.firebaseapp.com',
    storageBucket: 'popcorntime-4b65b.firebasestorage.app',
    measurementId: 'G-32GKH2117M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_2_2DlZxpkpz7i2__yw8dk5Nvge8HZo',
    appId: '1:636444728768:android:37dd01265099980df7fc25',
    messagingSenderId: '636444728768',
    projectId: 'popcorntime-4b65b',
    storageBucket: 'popcorntime-4b65b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgfIR9OawdfUBdtSXzexgDQ_FwJ5SUQcA',
    appId: '1:636444728768:ios:4b90f8770042b107f7fc25',
    messagingSenderId: '636444728768',
    projectId: 'popcorntime-4b65b',
    storageBucket: 'popcorntime-4b65b.firebasestorage.app',
    iosBundleId: 'com.example.popcorntime',
  );
}
